export {default as BECOME_STREAMER} from './images/Become_streamer.png';
export {default as BECOME_STREAMER_ARC} from './images/become_stremer_arc.png';
export {default as BLACK_CAR} from './images/black-car.png';
export {default as CAR_DETAIL} from './images/car-detail.png';
export {default as WHITE_CAR} from './images/white-car.png';
export {default as RED_CAR} from './images/red-car.png';
export {default as SILVER_CAR} from './images/silver-car.png';
export {default as TYRE} from './images/tyre-rep.png';
export {default as RECTANGLE} from './images/rectangle.png';
